spring:
  mail:
    host: smtp.qq.com
    username: ENC(5CSiFNWbI8kmmubimO+mEThdaNPp0IaTE6mA22qHV77T2gHjAcu66eH8k3Xkrq8S)
    password: ENC(oirUCPalCo8oGqRYBUw2/e6cxcXLM4eHufwB6YJjDAOIhpQInA89D9I8BLwVfKA/)
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true

jasypt:
  encryptor:
    password: test